### ISSUE TITLE
Should those strings be identical?

### ISSUE THREAD

**Issue by elbotho** [serlo/ece-as-a-service#101]
https://github.com/serlo/ece-as-a-service/blob/main/src/editor/editor.tsx#L113
https://github.com/serlo/ece-as-a-service/blob/main/src/editor/toolbar.tsx#L80

**Comment by kulla** [comment]
yep, if you want you can add a variable where it is set.

**Comment by elbotho** [comment]
solved in f817bc50c92a6ba346a6d46caae9c62e622af803
