### ISSUE TITLE
Add documentation for the deeplink flow of the editor

### ISSUE THREAD

**Issue by kulla** [serlo/ece-as-a-service#110]
Save it in https://github.com/serlo/documentation/wiki

**Comment by LarsTheGlidingSquirrel** [comment]
Created [documentation page in serlo wiki](https://github.com/serlo/documentation/wiki/Integration-of-the-Serlo-Editor-in-Edusharing-(RLP-integration)) and added section about Deep Link flow initiated when user wants to embed content from Edusharing within the editor.

**Comment by kulla** [comment]
Perfect! 👍
