### ISSUE TITLE
Check response_type in Authentication Request to /platform/login

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/ece-as-a-service#125]
According to the OpenID Connect spec, the Authentication Request is required to contain a response_type, see: https://openid.net/specs/openid-connect-core-1_0.html Section: 3.1.2.1

This parameter apparently defines what should be sent back. In our case an id_token.

**Comment by kulla** [comment]
Since we do not use this parameter we will not implement this
