### ISSUE TITLE
Check if lti_message_hint{user, dataToken, nodeID} in Authorization Request matches what was sent in Login Request

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/ece-as-a-service#128]
When crafting the Login Request in /lti/start-edusharing-deeplink-flow we supply a lti_message_hint that encodes the user, dataToken and nodeId. 

Edusharing will send this back without modification in the Authentication Request. We need to check if the value here matches what was sent earlier. See: https://www.imsglobal.org/spec/lti/v1p3/#lti_message_hint-login-parameter

**Comment by kulla** [comment]
Good point -> we can store it in the mongo db since we already have a flow id. Then we do not need to send `lti_message_hint` any more
