### ISSUE TITLE
Edusharing-Asset-Plugin does not get focus when iframe is clicked

### ISSUE THREAD

**Issue by kulla** [serlo/ece-as-a-service#15]
When an edusharing asset plugin (see #14) is rendered with an iframe and the iframe is clicked it doesn't get focus since the iframe eats the click event / the click event is not recognizable in the editor (see https://stackoverflow.com/questions/2381336/detect-click-into-iframe-using-javascript for possible solutions), maybe https://developer.mozilla.org/en-US/docs/Web/HTML/Element/portal can be used in the future.

**Comment by elbotho** [comment]
(maybe manually dispatch edtr focus event)

**Comment by elbotho** [comment]
solved in 750c1904e75748038ee9974c1b72529cb2230d09 by disabling pointer events on the iframe in general. Interaction with the iframe content should not be necessary so this actually simplifies the experience. 

Work in Mac on Safari, Chrome, Firefox, Opera.
