### ISSUE TITLE
Remove need for cookie deeplinkFlowId

### ISSUE THREAD

**Issue by kulla** [serlo/ece-as-a-service#169]

**Comment by LarsTheGlidingSquirrel** [comment]
A thought on this: 

lti.js already established a session with the browser using cookies, when the editor was launched as a tool. We already use this in our implementation in e.g. /lti/start-edusharing-deeplink-flow. There, the lti.js middleware validates that the browser cookie that was sent with the request belongs to an active session in the DB. Also the ltik token is verified. If all check succeed, the request gets forwarded to our request handler containing the user information. 

Idea: We could use this for other endpoints as well, like /platform/login.
