### ISSUE TITLE
Add test: LTI launch fails with error message if content json sent by edu-sharing is malformed.

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/ece-as-a-service#189]
When the content json sent by edu-sharing in the response of {edu-sharing}/rest/ltiplatform/v13/content is malformed, there should be an error message that helps debugging this.

**Comment by LarsTheGlidingSquirrel** [comment]
Currently, it looks like we might access properties in the returned json that might be undefined. In migrate(...) in /src/shared/storage-format/index.ts

**Comment by kulla** [comment]
> Currently, it looks like we might access properties in the returned json that might be undefined. In migrate(...) in /src/shared/storage-format/index.ts

Can you be more specific?
