### ISSUE TITLE
How to handle property "document" being null in response json of /lti/get-content?

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/ece-as-a-service#192]
In recent tests with the edusharing deploy, the json returned by lti/get-content contained:
document: null
This might have been the cause of an error message in a user test. 

How should we handle document === null? 
Disallow and show error? Or show empty document?

**Comment by LarsTheGlidingSquirrel** [comment]
I think showing an empty document would be fine. The next time the document is saved should hopefully make further requests return document !== null.

**Comment by kulla** [comment]
Is it `null` or `undefined`?! -> Actually this should never occur and a error message might be a better thing to show.

**Comment by LarsTheGlidingSquirrel** [comment]
It is null. The returned json for file Testing1234 on https://repository.edusharing-81.81.134.76.15.243.nip.io/edu-sharing/components/render/f6696870-c4e1-4845-9486-2da18167d105 is:
{"type":"https://github.com/serlo/ece-as-a-service","version":0,"document":null}

In PR https://github.com/serlo/ece-as-a-service/pull/190 it was changed so that "document" cannot be null and an error message will be displayed instead. So in the next deploy, this should be handled correctly on our end. But edu-sharing might still need to apply a fix for this.

**Comment by kulla** [comment]
See #195 and #194
