### ISSUE TITLE
Move jest tests that require a working edu-sharing test double that returns keyset into a single test file. 

### ISSUE THREAD

**Issue by LarsTheGlidingSquirrel** [serlo/ece-as-a-service#197]
Currently, in two test files (__tests__/editor.ts and __tests__//editor-lti-endpoints.ts) we have setup and teardown code that sets up an express server that provides the keyset used to verify jwt signatures. 
Tests requiring this test double could be moved into a single file. This would reduce code duplication and also enable us to run other test files in parallel again.

**Comment by kulla** [comment]
Unfortunately this will not work since in jest each test file runs in a separate process / with a separate global state (see https://github.com/facebook/jest/issues/7184 or https://stackoverflow.com/a/60576129 )
