### ISSUE TITLE
Test for saving of document

### ISSUE THREAD

**Issue by kulla** [serlo/ece-as-a-service#205]

**Comment by LarsTheGlidingSquirrel** [comment]
@kulla Do you see the need for any additional tests apart from:
- Saving each 5s
- Saving when user clicks save button
- Saving when browser window/tab is closed
Those are already addressed in other issues and implemented in #211

**Comment by kulla** [comment]
> @kulla Do you see the need for any additional tests apart from:
> 
>     * Saving each 5s
> 
>     * Saving when user clicks save button
> 
>     * Saving when browser window/tab is closed
>       Those are already addressed in other issues and implemented in [test: add tests for saving automatically #211](https://github.com/serlo/ece-as-a-service/pull/211)

Yep, there was a reason why I added it (must have been in our last meeting) -> I guess the other issues already cover this topic well
