### ISSUE TITLE
Incognito mode blocks sessionStorage and throws error

### ISSUE THREAD

**Issue by CodingDive** [serlo/ece-as-a-service#271]
Steps to reproduce
1. Run yarn dev
2. Open web app in Incognito

The iframe content does not load at all. 

![image](https://github.com/serlo/serlo-editor-for-edusharing/assets/28842311/63db400e-78c3-46fa-9532-bd778c35fc1e)

According to https://stackoverflow.com/questions/24456891/iframe-in-chrome-error-uncaught-securityerror-failed-to-read-the-sessionstora this is caused by script blockers or blocking third party cookies/site-data.

**Comment by hugotiburtino** [comment]
Is it still relevant?
If not, please close the issue.
If yes, please transfer to the repo `serlo/serlo-editor-as-lti-tool`

**Comment by hugotiburtino** [comment]
I've tested in the serlo/serlo-editor-as-lti-tool and it seems to work. So, closing this issue
