### ISSUE TITLE
Add unit testing

### ISSUE THREAD

**Issue by kulla** [serlo/ece-as-a-service#29]
Add unit testing with jest. Test cases: 

- [x] Open editor with LTI
- [ ] Open editor in view mode when `postContentApiUrl` is not present (see https://github.com/serlo/ece-as-a-service/commit/f9eaf79ad821985dcabecdb5ae360e60fc54f990)
- [ ] ~Add code coverage~ -> #121 
- [x] Button "Close and save"
- [x] Button "name version"
- [ ] Content is automatically saved after 5secs
- [x] Content is saved with a comment when closed with a tab
- [ ] ~Calls for LTI (like keyset URLs)~ -> #122 
- [x] Deeplink-Call?! -> #109

**Comment by ortwic** [comment]
Is the deeplink call still relevant?

**Comment by kulla** [comment]
All leftover tests are planned in other issues...
